# Generated by Django 3.0.4 on 2020-11-02 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201026_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_slug',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=2083),
            preserve_default=False,
        ),
    ]
