# Generated by Django 3.0.4 on 2021-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210124_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
