# Generated by Django 3.0.4 on 2021-01-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_wallpaper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='id_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
